include: ../latent/imagenet1k_sdvae_latents_table8_b2_closest_feasible_single_gpu.yaml
tier: stable
canonical-config: configs/latent/imagenet1k_sdvae_latents_table8_b2_closest_feasible_single_gpu.yaml
