include: ../experimental/latent/imagenet1k_sdvae_latents_table8_ablation_default_template.yaml
tier: experimental
canonical-config: configs/experimental/latent/imagenet1k_sdvae_latents_table8_ablation_default_template.yaml
